import type { Metadata } from "next";
import { Quicksand } from "next/font/google";
import "./globals.css";
import "@solana/wallet-adapter-react-ui/styles.css";

import AppProvider from "@/components/AppProvider";

const geistSans = Quicksand({
  variable: "--font-geist-sans",
  weight: ["300", "400", "500", "600", "700"],
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.className}  antialiased bg-yellow-50/50`}>
        <AppProvider>{children}</AppProvider>
      </body>
    </html>
  );
}
