import type { Metadata } from "next";
import {
  Dosis,
  Geist,
  Geist_Mono,
  Quicksand,
  Roboto_Flex,
} from "next/font/google";
import "./globals.css";

const geistSans = Quicksand({
  variable: "--font-geist-sans",
  weight: ["300", "400", "500", "600", "700"],
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.className}  antialiased`}>{children}</body>
    </html>
  );
}
