import type { Metadata } from "next";
import { Dosis, Geist, Geist_Mono, Roboto_Flex } from "next/font/google";
import "./globals.css";

const geistSans = Roboto_Flex({
  variable: "--font-geist-sans",
  weight: ["200", "300", "400", "500", "600", "700", "800", "100", "900"],
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.className}  antialiased`}>{children}</body>
    </html>
  );
}
